# Generated by Django 6.0.4 on 2026-06-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='categoria',
            field=models.CharField(default='Consulta General', editable=False, max_length=50),
        ),
    ]
