# Generated by Django 6.0.4 on 2026-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca_app', '0003_usuariopermitido_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopermitido',
            name='apellido',
            field=models.CharField(default='', max_length=100),
        ),
    ]
