# Generated by Django 6.0.4 on 2026-07-29 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinoteca_app', '0004_usuariopermitido_apellido'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoNosotros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_historia', models.CharField(default='Nuestra Historia', max_length=200, verbose_name='Título Historia')),
                ('parrafo1_historia', models.TextField(default='Fundada en el corazón del Valle de Uco, nuestra bodega nació de un sueño familiar: transformar la pureza del agua de montaña y la fuerza del sol mendocino en vinos con alma.', verbose_name='Historia - Párrafo 1')),
                ('parrafo2_historia', models.TextField(default='Desde hace tres generaciones, mantenemos el compromiso de intervenir lo menos posible en el proceso natural, permitiendo que cada botella sea un reflejo fiel de su terruño.', verbose_name='Historia - Párrafo 2')),
                ('titulo_secreto', models.CharField(default='El Secreto', max_length=200, verbose_name='Título El Secreto')),
                ('parrafo1_secreto', models.TextField(default='Creemos que el vino se hace en el viñedo. Por eso, cuidamos nuestras vides con técnicas orgánicas y una cosecha manual que respeta los tiempos de la naturaleza.', verbose_name='El Secreto - Párrafo 1')),
                ('parrafo2_secreto', models.TextField(default='La altitud y la amplitud térmica de nuestra zona nos brindan uvas de una concentración y frescura excepcionales, que luego descansan en barricas de roble francés.', verbose_name='El Secreto - Párrafo 2')),
                ('ultima_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contenido de Nosotros',
                'verbose_name_plural': 'Contenido de Nosotros',
            },
        ),
    ]
